### ISSUE TITLE
Release date for book?

### ISSUE THREAD

**Issue by cdancy** [BruceEckel/OnJava8-Examples#23]
Just curious if there was anything concrete or even a ballpark figure on when you might be releasing something.

**Comment by BruceEckel** [comment]
I've been working on the book for over 1 1/2 years. Most of the chapters are in very good shape, and there are three that are still unfinished:

1. One chapter is quite close to being done.
2. One chapter needs more work
3. The "threads" chapter (always my nemesis) has had months of research done, but stills require a fair amount of development and writing.

My current plan is to release an early-access version on Google Books. This will provide a way to start getting feedback, and incorporating it into updates. However, for many people what's there now will be most of what they need. I can do that as soon as Google Books re-opens for publisher signups, which they say is "soon" but of course that could mean a lot of things. Also, I think Google Books will satisfy my needs, but it's always possible I'll discover that they have some constraint or requirement I can't live with, and that will set things back.

Apart from that I hope to finalize the project within the next 3 months, but with concurrency one never knows. If I can do the early-access thing that will take most of the pressure off for people who have been anxious about getting it right now.

**Comment by cdancy** [comment]
@BruceEckel fair enough. I noticed @bmuschko sending in commits (I help to maintain one of his projects) and recognized your name which I haven't heard since my days in high school when I learned to program from reading `Thinking in Java`. If you need any help, be it looking over java or gradle code, I'd be more than happy to lend a helping hand in whatever way I can.

**Comment by BruceEckel** [comment]
Since you offered gradle help, I have what I hope is a final snag in my build. When I say:

gradlew test

There are compile errors because it's missing JMH classes, even though the test process doesn't use JMH (and commands like "gradlew validating:jmh" work fine).

My guess is that I either need a "compile" dependency in the test configuration, or the test setup needs to somehow exclude the jmh files, but it's not clear to me how to proceed. Your assistance would be appreciated.

**Comment by cdancy** [comment]
@BruceEckel do you have a stacktrace from the error to look at?

`./gradlew --stacktrace clean build`

**Comment by wawlian** [comment]
@BruceEckel Are these examples for the new version of Thinking in Java or for a totally new book emphasise on Java 8 new features？

**Comment by BruceEckel** [comment]
Totally separate book titled "On Java 8"

**Comment by bmuschko** [comment]
@cdancy I sent the solution to @BruceEckel's question to him by mail. No more need to have a deeper look.
