### ISSUE TITLE
Testing Object Equivalence

### ISSUE THREAD

**Issue by altgeek** [BruceEckel/OnJava8-Examples#29]
The output is:
/* Output:
true
false */

"Surely the output should be “true”, then “false,” since both Integer objects are the same."

This is the case, I tested it.

The book says "the output is actually “false”, then “true.”"

This doesn't match the output.

If I used new Integer ( 47 ) on the assignment for n1 and n2, then your second statement works.

(p.s. I am aware of the Integer cache for values -128 to 127 , so the simple example in the book has even more unwanted nuances.)

**Comment by nhbarn** [comment]
Was also confused by this.  If the values assigned to the Integer objects are outside the -128 to 127 range, then the output will match the text explanation.  The values used (47) causes it to fall into the exception due to cached numbers.  So there are two learning opportunities here: equivalence of references vs values and the existence of the Integer class cache.  As noted above, if you force the object to its own reference with the "new Integer", the text also holds as written.

**Comment by BruceEckel** [comment]
From an email:

Hi Bruce,

I noticed an error on your book on Testing Object Equivalence


Initializing Integer n1 = 47 and Integer n2 = 47 will go as true and false in the comparison you make, however when initialized with Integer n1 = new Integer(45) and Integer n2 = new Integer(45) will produce the false and true output as described.

I guess there should be an update there on the “new” initialization.

Best regards,
Dragos

**Comment by BruceEckel** [comment]
Fixed. Examples are available now, prose will appear in next Leanpub update but can be found here: https://www.bruceeckel.com/2021/02/04/java-object-equivalence/

**Comment by altgeek** [comment]
> Fixed. Examples are available now, prose will appear in next Leanpub update but can be found here: https://www.bruceeckel.com/2021/02/04/java-object-equivalence/

Bruce, is there any upgrade path for the newest/corrected edition for those of us that bought the initial release on google books?

**Comment by BruceEckel** [comment]
I'm slowly trying to figure out something to do for that. Probably the best
solution in the short term is to email me (BruceTEckel@gmail.com) and I can
send you a pass to the Leanpub book.

*Bruce Eckel*
MindViewLLC.com
Blog: BruceEckel.com
EvolveWork.co
WinterTechForum.com <http://www.WinterTechForum.com>
OnJava8.com <http://www.OnJava8.com>
www.AtomicKotlin.com
Reinventing-Business.com <http://www.Reinventing-Business.com>

**Comment by BruceEckel** [comment]
PS: I've updated the Google Play Books version to reflect the current book.

*Bruce Eckel*
MindViewLLC.com
Blog: BruceEckel.com
EvolveWork.co
WinterTechForum.com <http://www.WinterTechForum.com>
OnJava8.com <http://www.OnJava8.com>
www.AtomicKotlin.com
Reinventing-Business.com <http://www.Reinventing-Business.com>
