### ISSUE TITLE
Using Gradle 4.4 and Java 9.0.1 with the OnJava8 examples

### ISSUE THREAD

**Issue by MikePolinske** [BruceEckel/OnJava8-Examples#30]
Bruce,
I'm new to Java and especially Gradle.  I have Java 9.0.1 installed on macOS 10.13.3 and because the gradle wrapper was downloading 3.5 which I had seen isn't compatible with Java 9.0.1, I updated the gradle-wrapper.properties to point to the latest version of gradle, which is 4.4.

The gradlew command still failed, so I ran in with the --scan option and here is the link to my build scan: https://scans.gradle.com/s/7xszx4p464is4

It looks like it is having a problem with the tagging plugin.

Any suggestions?

Thank you.

**Comment by BruceEckel** [comment]
For the moment I think your only choice is to roll back to Java 8 and Gradle 3.5; the issue is Gradle's lack of backward-compatibility.

If you really want to use Java 9 right now, you can compile the examples using the command-line compiler and skip Gradle.

**Comment by MikePolinske** [comment]
Thank you Bruce.  I removed JDK 9 and was able to successfully run the gradlew run command with JDK 1.8.0-151.

I had tried using jenv (http://www.jenv.be/) pointing to my JDK 1.8, but Gradle was still balking that it saw 9.0.1 on my system.

Now I can continue with the book.
