### ISSUE TITLE
Comments in Overloading.java is confusing

### ISSUE THREAD

**Issue by sivanesanms** [BruceEckel/OnJava8-Examples#34]
`public class Overloading {
    public static void main ( String [] args) {
       for ( int i = 0 ; i < 5 ; i++) { 
          Tree t = new Tree (i); // Overloaded constructor
             t. info (); 
             t. info ( "overloaded method" ); 
        } 
       new Tree (); 
   }
}`

The comment //Overloaded constructor should be here.

**Comment by BruceEckel** [comment]
Has been fixed for awhile. Sorry for leaving this issue open.
