### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by xianfuxing** [BruceEckel/OnJava8-Examples#36]
I am new to Java, build failed on Centos7 & openjdk 1.8:
` ./gradlew run`
`FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Desktop\OnJava8-Examples\build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'OnJava8-Examples'.
> Failed to apply plugin [id 'com.mindviewinc.tagging']
   > java.lang.NullPointerException (no error message)`

Could anyone give advise? Thanks.

**Comment by ratsafalig** [comment]
same problem here wish anyone give advise

**Comment by ratsafalig** [comment]
somehow remove the`apply plugin: 'com.mindviewinc.tagging'`from build.gradle works for me

**Comment by qingbol** [comment]
> somehow remove the`apply plugin: 'com.mindviewinc.tagging'`from build.gradle works for me

works for me too. But why?

**Comment by MarceluitNL** [comment]
Worked for me too!

**Comment by BruceEckel** [comment]
This should be resolved now.
