### ISSUE TITLE
Could not determine java version from '11.0.7'

### ISSUE THREAD

**Issue by MScofied** [BruceEckel/OnJava8-Examples#40]
I completed all the steps include the 'choco install jdk8' and java -version also works on my computer. However, when it comes to "gradlew run", i cannot run it.
 It show the error "Could not determine java version from '11.0.7'" 

Please help. I can't execute any of the examples in this repository. Please help

**Comment by BruceEckel** [comment]
Should be fixed in the latest:
https://github.com/BruceEckel/OnJava8-Examples/releases/tag/v2.0
