### ISSUE TITLE
Is the parameter redundant

### ISSUE THREAD

**Issue by nengquqiaoxiaoyun** [BruceEckel/OnJava8-Examples#42]
In _Thinking In Java_, Chapter 14.3
Here is the class PetCount:
```java
// typeinfo/PetCount.java
...

public class PetCout {
...

   public static void countPets(PetCreator creator) {
       PetCounter counter = new PetCounter();
           for(Pet pet : creator.createArray(20)) {
              ...  
          }
   }
}
```
Here is used creator to create Pet[].
----
In _On Java 8_
Here is the class PetCount:

```java
// typeinfo/PetCount.java
...

public class PetCout {
...

   public static void countPets(PetCreator creator) {
       PetCounter counter = new PetCounter();
           for(Pet pet : Pets.array(20)) {
              ...  
          }
   }
}
```
Here is used Pet's method array to create Pet[], and  there is a Creator in class Pets, the instance is LiteralPetCreator 

```java
// typeinfo/pets/Pets.java
// Facade to produce a default PetCreator

public class Pets {
    public static final PetCreator CREATOR = new LiteralPetCreator();

    public static Pet[] array(int size) {
        Pet[] result = new Pet[size];
        for (int i = 0; i < size; i++)
            result[i] = CREATOR.get();
        return result;
    }

}
```

original text：
> Because PetCount.countPets() takes a PetCreator argument, we can easily test the LiteralPetCreator (via the above Façade): 
// typeinfo/PetCount2.java import typeinfo.pets.*;
public class PetCount2 { 
    public static void main(String[] args) { 
        PetCount.countPets(Pets.CREATOR); 
    }
}

We create Pet[] by Pet's method, and we do not need test the LiteralPetCreator like this
` PetCount.countPets(Pets.CREATOR); `
The LiteralPetCreator is in class Pets

**Comment by nengquqiaoxiaoyun** [comment]
`PetCount.countPets(null);`
This also works

**Comment by BruceEckel** [comment]
Thank you so much for pointing this out. I had started to transform these
examples and got sidetracked. I've been reworking and improving the
examples in the chapter and the (significantly changed) results will appear
in the next update on Leanpub.

*Bruce Eckel*
MindViewLLC.com
Blog: BruceEckel.com
EvolveWork.co
WinterTechForum.com <http://www.WinterTechForum.com>
OnJava8.com <http://www.OnJava8.com>
www.AtomicKotlin.com
Reinventing-Business.com <http://www.Reinventing-Business.com>
