### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Big-Chang** [BruceEckel/OnJava8-Examples#44]
After ./gradlew run
i got this:
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/Users/unkownName/Java/OnJava8-Examples-master/settings.gradle' (/Users/unkownName/.gradle/caches/6.7.1/scripts/edk6mvnjzpgssksovx4yqscbc).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 60

**Comment by BruceEckel** [comment]
Couldn't reproduce on Windows or Linux. Is this on a Mac? This has a lot of updates including the latest Gradle 6.8.1 so I think it might fix it:
https://github.com/BruceEckel/OnJava8-Examples/releases/tag/v2.0
