### ISSUE TITLE
Please consider a minor fix

### ISSUE THREAD

**Issue by TonySFU** [BruceEckel/OnJava8-Examples#45]
Hi Bruce,

I was using VSCode on Mac and try to `gradlew` build this pkg. Somehow VSCode create a `.settings` dir and cause a build failure.
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':.settings'.
> The project name '.settings' must not start or end with a '.'. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/6.8.1/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
```

it took me couple hours to find and fix this problem.

Please consider use `!file.name.startsWith('.')` to avoid this problem

https://github.com/BruceEckel/OnJava8-Examples/blob/d97d374947cfefc2a2577507e4ff47824977baaf/settings.gradle#L3-L5

Thanks,
Tony

**Comment by BruceEckel** [comment]
Try it now.
