### ISSUE TITLE
Support for building and running the source code in IDEA

### ISSUE THREAD

**Issue by gongzelong0718** [BruceEckel/OnJava8-Examples#50]
Hi Bruce,

Will you consider to add support or instructions for building and running the source code in IDEA?
For the beginner, it is convenient to build and run the source code in IDEA.

But it seems that after importing the project, it does not show the run icon.
Are you writing all the source codes without modern IDE?

Here is what I got when I tried to run the main method in IDEA...

<img width="1678" alt="Screen Shot 2021-06-26 at 12 53 49 PM" src="https://user-images.githubusercontent.com/6286811/123502382-80334880-d67e-11eb-941c-3e82c401030a.png">

**Comment by BruceEckel** [comment]
The Gradle file was designed for standalone compilation, unfortunately.

**Comment by zhouyao1994** [comment]
> Hi Bruce,
> 
> Will you consider to add support or instructions for building and running the source code in IDEA? For the beginner, it is convenient to build and run the source code in IDEA.
> 
> But it seems that after importing the project, it does not show the run icon. Are you writing all the source codes without modern IDE?
> 
> Here is what I got when I tried to run the main method in IDEA...
> 
> <img alt="Screen Shot 2021-06-26 at 12 53 49 PM" width="1678" src="https://user-images.githubusercontent.com/6286811/123502382-80334880-d67e-11eb-941c-3e82c401030a.png">

i met the some preblem with you ~

**Comment by cdh111007** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
